
#table state 
table_state=Delete:删除:0,Complete:完成:1,Unfinished:未完成:2
check_state=Unaudited:未检查:0,Approved:通过:1,Nopass:未通过:2
examine_state=Unaudited:未审核:0,Approved:通过:1,Nopass:未通过:2
stock_in=Produce:生产入库:1,Buy:采购入库:2,Other:其他入库:3
lost_state=Outlost:出库损耗:1,Inlost:入库损耗:2,Naturelost:自然损耗:3,Otherlost:其他:4

#Threshold options

Materiel_abc=TypeA:A类警报阀值:30%,TypeB:B类警报阀值:20%,TypeC:C类警报阀值:30%
Materiel_enough=AMax:A类最大阀值:70%,AMin:A类最小阀值:30%,BMax:B类最大阀值:70%,BMin:B类最小阀值:30%,CMax:C类最大阀值:70%,CMin:C类最小阀值:30%
Data_date=20
